# -*- coding: utf-8 -*-
"""Task 3_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uov0ASChK-YAW8MGPYVz8GxNDxC-13DA

#Student Grades
"""

#creating a list of dictionaries representing students
students = [
    {"name" : "Ahmed", "grades" : [7, 8, 9]},
    {"name" : "Mohamed", "grades" : [6, 7, 8]},
    {"name" : "Ali", "grades" : [9, 10, 8]}
]

# Calculating and printing the average grade for each student
for student in students:
    average_grade = sum(student['grades']) / len(student['grades'])


    print(f"{student['name']},Average Grade: {int(average_grade)}")