# -*- coding: utf-8 -*-
"""Task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IECwq9g3dop8ltFEae5FRDSXpvsP0m0z

#Contact Book
"""

#Create the contacts dictionary
contacts = {
    "Ahmed": "01000",
    "Mohamed": "02000",
    "Ali": "03000"
}

#Print all names in the contact book
print("Contacts:")

for name in contacts.keys():
    print(name)

#Allow user to search for a contact by name
name = ("Ahmed")
if name in contacts:
    print(f"{name}'s phone number is {contacts[name]}")
else:
    print("Contact not found.")